### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by happy-san**

### CODE REVIEW

**Review by Chetan-Goyal — APPROVED** [review]
LGTM

**Comment by Chetan-Goyal** [comment]
I was trying to do some more changes as per Grammarly's suggestions but it opened a new PR.

**Comment by happy-san** [comment]
There's an option to allow edits by maintainers, maybe I had that turned off. Regardless, go ahead open a new pr.

**Comment by Chetan-Goyal** [comment]
Those were very minor updates and not that significant. I thought it will be merged in that PR since I was not getting any option to edit on this one. We can skip them. No worries.

**Pull request merged**
